name: Cloudsmith CLI Setup
description: Set up Cloudsmith CLI in GitHub Actions
author: BartoszBlizniak
inputs:
  cli-version:
    description: "A specific version of the Cloudsmith CLI is installed/used."
    default: ''
    required: false
  api-key:
    description: 'API Key for Cloudsmith'
    default: ''
    required: false
  oidc-namespace:
    description: 'Cloudsmith organisation/namespace for OIDC'
    default: ''
    required: false
  oidc-service-slug:
    description: 'Cloudsmith service account slug for OIDC'
    default: ''
    required: false
  oidc-auth-only:
    description: 'Only perform OIDC authentication without installing the CLI'
    default: 'false'
    required: false
  oidc-auth-retry:
    description: 'Number of retry attempts for OIDC authentication (0-10)'
    default: '3'
    required: false
  oidc-token-validate:
    description: 'Validate the OIDC token after authentication'
    default: 'true'
    required: false
  pip-install:
    description: 'Install the Cloudsmith CLI via pip'
    default: 'false'
    required: false
  executable-path:
    description: 'Path where the Cloudsmith CLI is downloaded'
    required: false
  api-host:
    description: 'API Host for Cloudsmith'
    default: ''
    required: false
  api-proxy:
    description: 'API Proxy for Cloudsmith'
    default: ''
    required: false
  api-ssl-verify:
    description: 'Verify SSL certificates for Cloudsmith API'
    default: ''
    required: false
  api-user-agent:
    description: 'User Agent for Cloudsmith API'
    default: ''
    required: false
outputs:
    oidc-token:
        description: "JWT token generated by the Cloudsmith CLI setup action"
runs:
  using: 'node20'
  main: "dist/index.js"

branding:
  icon: 'box'
  color: 'blue'