name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Create release and move major tag
    runs-on: ubuntu-latest
    concurrency: release-major
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag format
        id: validate
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format: $TAG. Expected vMAJOR.MINOR.PATCH" >&2
            exit 1
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Update floating major tag
        run: |
          TAG="${GITHUB_REF_NAME}"
          MAJOR=$(echo "$TAG" | cut -d. -f1)
          echo "Updating $MAJOR to point at $TAG (commit $GITHUB_SHA)".
          # Create/force-update annotated tag for auditability
          git tag -fa "$MAJOR" -m "Point $MAJOR to $TAG"
          git push origin "$MAJOR" --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}